### ISSUE TITLE
Debugging installed garment package is broken

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#10]
## Issue Report

When I have garment installed locally, in order to debug, I have to delete the source map comments to debug the compiled JS files since the original TS files aren't included in the package.

(A clear and concise description of the issue)

## Expected Behavior

(Write out the expected behavior here.)
Either no map files are included, or the original TS files are included with the map files.

## Actual Behavior

(Write out what actually happened here.)
Here's an excerpt of my node_modules directory :

![image](https://user-images.githubusercontent.com/34415120/89712725-9f53b980-d98a-11ea-9799-d77e5cbaa6e9.png)

The bottom of each js file will have the correct url to the map file, however, because the TS files aren't included in node_modules, it won't be able to find them.  I'll get an error of could not find file in Chrome Node Inspector.

## Steps to Reproduce the Issue

(Write out detailed steps to reproduce the issue here.)
Install garment

## Proposal

Either
 

1.   Remove "sourceMap": true, from tsconfig.base.json (easier and low maintenance overhead, but not as user-friendly debugging experience), or 
2.   Include the ts files along with lib in every garment package (more maintenance overhead, but better debugging experience).  

I'd prefer 2 myself.

I can make the PR depending on which you decide, or include it in the PR I already have open if you'd prefer.

**Comment by beshanoe** [comment]
now there should be no source maps in the package https://github.com/Farfetch/garment/pull/20
