### ISSUE TITLE
platform-specific tests are causing unit tests to fail on Windows

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#3]
## Issue Report
Unit tests are failing on a clean Windows master build.

## Expected Behavior

After a clean clone, yarn, and build, running unit tests should pass on any platform.

## Actual Behavior

On my windows machine, the unit tests are failing.  It seems to have to do with platform-specific paths.

## Steps to Reproduce the Issue

1. Checkout the master branch 
2. Run yarn install 
3. run yarn build 
4. Run yarn test runner-babel or any unit test that deals with paths

## Attempted failed solution

I tried installing jest-serializer-path , but it does not seem that this would solve the issue.  I would need a Mac computer to try.
Also, the last publish from this library was 2 years ago so I'm not sure about its quality.

**Before jest-serializer-path**:

![image](https://user-images.githubusercontent.com/34415120/88234880-a6cc5080-cc71-11ea-86ce-8ca7e9c938d2.png)

**After jest-serializer-path**:

![image](https://user-images.githubusercontent.com/34415120/88234955-c9f70000-cc71-11ea-90f1-3e62142aba39.png)

If someone could try jest-serializer-path on a Mac that would be great, but I don't see it turning the path I received using it, to those that were snapshotted.

**Comment by danielamaia** [comment]
@stephan-noel is working on this issue

**Comment by stephan-noel** [comment]
Just gonna leave some notes here on what I found regarding that test failure.  TLDR is that internally, `ts.createProgram()` is invoking `ts.normalizePath()` which transforms our Windows-style path into a Unix-style path and therefore invokes the host's `readFile` function with a Unix-style path.

We could work around this by converting back to Windows-style paths in the readFile function, not sure if there are any dangers in that approach.

I'll leave a trail of debug printscreens here:

1. Here, we still have the Windows-specific path as our fileName. The culprit seems to be ts.normalizePath(), which at the level below on the call-stack, will give it a Unix path. Not sure if the scope of unionfs would affect this:

![image](https://user-images.githubusercontent.com/34415120/88455920-73f0ab00-ce71-11ea-9017-26175361983d.png)

2. One level below, at processSourceFile, we see the return value of ts.normalizePath() is a Unix-style path:

![image](https://user-images.githubusercontent.com/34415120/88455935-8e2a8900-ce71-11ea-853d-ebeb87740f65.png)

3.   Here, we are back in the ts-runner, where it will invoke readFile, with the unix-style path and where the error will occur when we invoke `ctx.fs.readFileSync()`:

![image](https://user-images.githubusercontent.com/34415120/88455946-a4384980-ce71-11ea-8e8d-1ccf62a59fe3.png)

Also of note, we will incorrectly get a cache miss because we registered the cache with Windows paths, and are doing a lookup with Unix paths.

Also, this seems to be the function for their normalizePath https://github.com/microsoft/TypeScript/blob/2a25901c546bbbffb5627589b9ea7091a3c9fc0d/src/compiler/path.ts .  At the top they have this "disclaimer":

![image](https://user-images.githubusercontent.com/34415120/88456081-b666b780-ce72-11ea-86e1-d45cc8ea8125.png)


What do you think is the best approach in this case?

**Comment by beshanoe** [comment]
@stephan-noel did we agree on converting the path back to the platform-specific in the runner-ts' custom host?

**Comment by stephan-noel** [comment]
@beshanoe yes we did, because they seem to use an internal interface to handle platform-specific code (it seems to be either toPath or an interface named System), at least from what I could tell.
