### ISSUE TITLE
Re-export types from @garment/runner

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#34]
Currently, certain types available on `Context` (single or batch mode) are not available from the `@garment/runner package`.  If I create helper functions/variables for any of these, this means I would have to add those dependencies explicitly to my runner.  I'm not sure what the best approach is in this case especially since some of these types are classes and we may not want to expose them directly to consumers.

Those I've identifies so far are:
- Project
- Logger

There are probably more and we should probably cover everything accessible from Context.

**Comment by gsferreira** [comment]
Closed due to project archival https://github.com/Farfetch/garment/pull/106
