### ISSUE TITLE
RFC: prettier-runner

### ISSUE THREAD

**Issue by joaopedrodcf** [Farfetch/garment#39]
In our project we use both `@garment/plugin-runner-eslint` and `@garment/plugin-runner-stylelint` but for `json files` we can't relly on eslint runner because eslint doesn't understand json synstax even by using the plugin `eslint-plugin-prettier` as you can see in the following issue https://github.com/prettier/eslint-plugin-prettier/issues/294

So what I propose is to create a generic runner `@garment/plugin-runner-prettier` that would make possible for projects that want to fix `json` files and other types of files that prettier also has the capability to be available for them.

So in the end, we could have a task like this:
```
    "lintable": {
      "tasks": {
        "lint": [
          {
            "runner": "eslint",
            "input": "{{projectDir}}/src/**/*.+(t|j)s?(x)",
            "output": "{{projectDir}}/src"
          },
          {
            "runner": "stylelint",
            "input": "{{projectDir}}/src/**/*.css",
            "output": "{{projectDir}}/src"
          },
         {
            "runner": "prettier",
            "input": "{{projectDir}}/src/**/*.json",
            "output": "{{projectDir}}/src"
          }
        ]
      }
    },
```

What do you guys think? 👋 
If you guys like the idea I would like to try to make it as my first contribution to the project 🙏

**Comment by luisvieiragmr** [comment]
i think this can be a good contribution, can you outline with more detail how you see this working? like how will it be configured? which configuration options will it take? will we use one config file for the whole repository or one per project?

**Comment by joaopedrodcf** [comment]
Hi @luisvieiragmr sorry for the late reply I wanted to make the example and show it to you but didnt had time.

So in terms of the API for the runner I was thinking to have 

```
configFile: path

The config file to load Prettier's configuration from.

fix: boolean 
// This fix if activated will use --write from prettier to fix the files
// Also fix is good because is the same as in eslint and stylelint runners, good for consistency

Fix automatically linting errors. 
```

This based on our `eslint-runner` in garment and also using the configs from prettier cli https://prettier.io/docs/en/cli.html

Then in our project in the lint staged we would do this 

```json
    "lint-staged": {
        "{**/*.js,**/*.ts,**/*.tsx,**/*.css,**/*.json}": [
            "garment lint --fix --files"
        ],
    },
```

that would run all the runners below

```json
    "lintable": {
      "tasks": {
        "lint": [
          {
            "runner": "eslint",
            "input": "{{projectDir}}/src/**/*.+(t|j)s?(x)",
            "output": "{{projectDir}}/src"
          },
          {
            "runner": "stylelint",
            "input": "{{projectDir}}/src/**/*.css",
            "output": "{{projectDir}}/src"
          },
         {
            "runner": "prettier",
            "input": "{{projectDir}}/src/**/*.json",
            "output": "{{projectDir}}/src"
          }
        ]
      }
    },
```

and we could run this `garment lint` on the pipelines as well.

What do you think?

**Comment by luisvieiragmr** [comment]
This seems nice! i would try it

**Comment by joaopedrodcf** [comment]
Okay gonna try it this week, expect news during the weekend 💪
