### ISSUE TITLE
configFile option in ts-runner does not support {{projectDir}}

### ISSUE THREAD

**Issue by stephan-noel** [Farfetch/garment#4]
## Issue Report

Trying to use `{{projectDir}}` in ts-runner gives an error.

Was using garment 0.13.3 but I expect 0.13.8 has the same behavior

```
"build": {
          "runner": "ts",
          "buildDependencies": true,
          "input": {
            "rootDir": "{{projectDir}}/src",
            "include": ["**/*.ts?(x)"],
            "exclude": [
             "somePathsToExclude"
            ]
          },
          "output": "{{projectDir}}/lib",
          "options": {
            "configFile": "{{projectDir}}/tsconfig.json"
          }
        }
```

## Expected Behavior

It should use the tsconfig.json file in my project directory.

## Actual Behavior

I get the following error.

![image (9)](https://user-images.githubusercontent.com/34415120/88235414-be580900-cc72-11ea-8d8e-0eea346f80e7.png)

## Steps to Reproduce the Issue

1. Use the ts-runner for a project
2. Use `{{projectDir}}` in the configFile option.

## Use Case 

I need this behavior because currently my shared tsconfig does not include `outDir` or `sourceRoot` and even if it did, I would have to change it for each project that I want to build in my monorepo.  I need `outDir` and `sourceRoot` because the .map file generated by tsc seems to depend on these properties to correctly refer to the original typescript file.  As is, I have to manually change the path in the .map file for this to work and when dependencies are built, these manual changes get overridden.

**Comment by beshanoe** [comment]
It's probably two separate issues, the one is most likely windows related bug in unionfs package and another is support for valid source maps

**Comment by stephan-noel** [comment]
I think this can be closed, 

`{{projectDir}}` is supported, however npm module syntax was the cause of the issue.  I made an issue here https://github.com/Farfetch/garment/issues/7.

**Comment by beshanoe** [comment]
ok, closing
