### ISSUE TITLE
npm also provides deterministic lockfile

### ISSUE THREAD

**Issue by jjangga0214** [Farfetch/garment#45]
Hi!

I read the sentence below from the README.

> We recommend the usage of yarn with due to its native workspaces support and deterministic lockfile

But as far as I know, npm also provides package-lock.json, whose role is equivalent to that of yarn.lock.

Maybe the sentence is a little bit misleading, and if you feel so, what about rewording the sentence?

Thanks!

**Comment by beshanoe** [comment]
Hi, thanks for pointing that out, we'll probably only leave the statement about a native monorepo support

**Comment by gsferreira** [comment]
Closed due to project archival https://github.com/Farfetch/garment/pull/106
