### ISSUE TITLE
typescript-runner tsconfig extends problem

### ISSUE THREAD

**Issue by joaopedrodcf** [Farfetch/garment#49]
# Issue Report

ts-runner, when one of the garment projects extends the `base tsconfig` of the root, will create the dist in the root of the project.

# Expected Behavior

It creates the `dist` in the root folder of a monorepo

# Actual Behavior

It should create the `dist` in the package of the garment project.

# Steps to Reproduce the Issue

While working on one of my projects I noticed a problem while trying to migrate to `garment`.

I'm using extends feature of `tsconfig` so I can have a `tsconfig.base.json` on root and then in each package I just extends this base.

`tsconfig.base.json`
```json
{
    "compilerOptions": {
        "target": "es2019",
        "module": "commonjs",
        "lib": ["es2019", "dom"],
        "jsx": "react-jsx",
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true,
        "composite": true,
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "noUncheckedIndexedAccess": true,
        "moduleResolution": "node",
        "types": [],
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "jsxImportSource": "@emotion/react",
        "resolveJsonModule": true
    }
}
```

`packages/button/tsconfig.json`
```json
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "outDir": "dist",
        "rootDir": "src"
    },
    "exclude": ["node_modules", "dist"]
}
```

The config I have on garment is the following for the build
```json
"build": {
    "runner": "ts",
    "input": "{{projectDir}}/src/**/*.ts?(x)",
    "output": "{{projectDir}}/dist",
     "options": {
        "configFile": "{{projectDir}}/tsconfig.json"
    }
 }
```

If I run from root ```yarn workspace @typescript-monorepo/button build``` which uses lerna and runs the following script ```tsc -b``` everything works correctly it generates a folder structure like this
![image](https://user-images.githubusercontent.com/11476152/112723913-b7bc1880-8f08-11eb-9c5c-96c13017e66c.png)

but if I do  ```yarn garment build button``` he creates the dist in the root dir
![image](https://user-images.githubusercontent.com/11476152/112723950-e33f0300-8f08-11eb-8289-a51011764838.png)

Im still trying to debug why this happens by running ```node --inspect-brk node_modules/@garment/cli/lib/cli.js``` and from what I find the Path.resolve is making the file to be on root dist

![image](https://user-images.githubusercontent.com/11476152/112726175-fdcaa980-8f13-11eb-899c-9665e0d7497a.png)

```js
// outPutPath = "C:/Users/joaof/Documents/projects/typescript-monorepo/packages/button/dist"
// file.path = "..\..\..\dist\button.js"
// fileDir = "C:\Users\joaof\Documents\projects\typescript-monorepo\dist"
// should have been 
// fileDir = "C:\Users\joaof\Documents\projects\typescript-monorepo\packages/button/dist"
const fileDir = Path.resolve(outPutPath, file.path);
```

The branch where the bug is in here: https://github.com/joaopedrodcf/typescript-monorepo/pull/7

**Comment by joaopedrodcf** [comment]
More info I learned from what I saw changing the `tsconfig` of one of my packages:
- Removing the extends and putting all the rules in here
- Removing the `"outDir": "dist"`

The tsconfig I made on the packages/button
```json
{
    "compilerOptions": {
        "target": "es2019",
        "module": "commonjs",
        "lib": ["es2019", "dom"],
        "jsx": "react-jsx",
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true,
        "composite": true,
        "strict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "noUncheckedIndexedAccess": true,
        "moduleResolution": "node",
        "types": [],
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "jsxImportSource": "@emotion/react",
        "resolveJsonModule": true,
        "rootDir": "src"
    },
    "exclude": ["node_modules", "dist"]
}
```

This makes the build be created in the right place and where the error appeared above it will be this
```js
// outPutPath = "C:/Users/joaof/Documents/projects/typescript-monorepo/packages/button/dist"
// file.path = "button.js"
// fileDir = "C:\Users\joaof\Documents\projects\typescript-monorepo\packages\dist"
const fileDir = Path.resolve(outPutPath, file.path);
```

So from my understanding the `file.path = "..\..\..\dist\button.js"` must be calculated from where the `tsconfig` was in this case the rootFile 🤔 

Gonna investigate more and put my findings here later.

**Comment by joaopedrodcf** [comment]
Okay did another test and with the following `tsconfig` the build works correctly

```JSON
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "rootDir": "src"
    },
    "exclude": ["node_modules", "dist"]
}
```

```js
// outPutPath = "C:/Users/joaof/Documents/projects/typescript-monorepo/packages/button/dist"
// file.path = "button.js"
// fileDir = "C:\Users\joaof\Documents\projects\typescript-monorepo\packages\dist"
const fileDir = Path.resolve(outPutPath, file.path);
```

So whenever we want to use `ts-runner` we cant use "outDir": "dist" what do you guys think we need to do to support this?

**Comment by beshanoe** [comment]
> So whenever we want to use `ts-runner` we cant use "outDir": "dist" what do you guys think we need to do to support this?

Hi, you've figured it right! 😁  
When I was creating this runner my idea was that you almost never have to use tsconfig.json per package, which is annoying when you have a lot of packages. Task's input and output clearly define where the build should go. That's why creating tsconfig in your case is pointless cause it's not overriding any compilerOptions
Secondly, I think the bug runner-ts has now is that it's not ignoring `outDir` option which leads to those kind of issues
