### ISSUE TITLE
Issue template doesnt appear when creating issue

### ISSUE THREAD

**Issue by joaopedrodcf** [Farfetch/garment#50]
## Bug Report

**Current Behavior**

The issue template that is configured in garment `.github/issue_templates` doesn't appear when creating an issue.

**Expected behavior**

When creating an issue this view should appear so we can select if it's a feature request or a bug.
![image](https://user-images.githubusercontent.com/11476152/112747488-cc062100-8fad-11eb-9207-00002f883903.png)

**Possible Solution**

Changing from `.github/issue_templates` to `.github/ISSUE_TEMPLATE` should make it start working.
We can also follow the tutorial to make it work https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by beshanoe** [comment]
Fixed
